# Generated by Django 5.1.1 on 2024-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('isbn_number', models.CharField(max_length=13)),
                ('pages', models.PositiveIntegerField()),
                ('lang', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
